### ISSUE TITLE
compatiblity of OS /bin/taskset PID affinty w/ OpenHFT Thread affinity

### ISSUE THREAD

**Issue by Cotton-Ben** [OpenHFT/Java-Thread-Affinity#10]
I assume that if you use OpenHFT Java-Thread-Affinity to  map a particular Java VM's  thread set to a specific pinned cpu  that it would completely over-ride any prior use of /bin/taskset to map that same JVM's PID to a different pinned cpu, correct?

Could there ever be a scenario where both /bin/taskset and OpenHFT Java-Thread-Affinity could work together w synergy?

Or is it generally true that because OpenHFT J-T-A offers a much higher resolution Thread-->CPU (instead of the coarse PID-->CPU) affinity capability that it effectively obsoletes the use of /bin/taskset?

**Comment by RobAustin** [comment]
closing as this was answered on 31 May 2014
