### ISSUE TITLE
support for java 11

### ISSUE THREAD

**Issue by mayur-who** [OpenHFT/Java-Thread-Affinity#101]
does this library support java 11? if yes, how can I integrate it with my maven pom.xml ?

**Comment by mayur-who** [comment]
@JorgeMag96 looks like you had created/updated java11 branch recently, can you please help with how I should import this library into my maven project which uses java11?

**Comment by JerryShea** [comment]
@mayur-who please use stackoverflow for questions. Java 11 is supported - see https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Java-Version-Support.adoc

**Comment by mayur-who** [comment]
sorry my bad, my repo was using older version and when I started using latest one 3.23.3, it just works.
