### ISSUE TITLE
Thread affinity to select performance or efficiency cores ?

### ISSUE THREAD

**Issue by eix128** [OpenHFT/Java-Thread-Affinity#109]
hi , it would be good to select

How to bind threads to performance (P) or efficiency (E) cores on java.
or select core which has AVX512
on apple i have seen
https://developer.apple.com/forums/thread/674456

**Comment by tgd** [comment]
Thanks for the feature suggestion @eix128 however this is not a priority for us at the moment. We do offer commercial support so please contact our sales team if you would like to bring this forward on our roadmap: https://chronicle.software/contact-us/
