### ISSUE TITLE
ExceptionInInitializerError occuring while try to run on Windows 7

### ISSUE THREAD

**Issue by ChandanKumar0125** [OpenHFT/Java-Thread-Affinity#23]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.test.thread.Test.main(Test.java:11)
Caused by: java.lang.NullPointerException
	at java.util.BitSet.and(Unknown Source)
	at net.openhft.affinity.AffinityLock.getReservedAffinity0(AffinityLock.java:113)
	at net.openhft.affinity.AffinityLock.<clinit>(AffinityLock.java:46)
	... 1 more

Cause:  public static final BitSet BASE_AFFINITY = Affinity.getAffinity();
BASE_AFFINITY  value is null and it is causing issue at reserverable.and(BASE_AFFINITY); line no:113

Affinity Version: 3.0
OS:  Windows 7
Java Version: 1.7.0_51-b13

**Comment by peter-lawrey** [comment]
This is bug in the NullAffinity implementation. I will add a fix.

This only appears if it fails to load the JNA in your application.  Which
version of JNA are you using?

**Comment by ChandanKumar0125** [comment]
I am using jna-4.2.0 the latest version available on github.

**Comment by peter-lawrey** [comment]
And you don't see any errors before this one.... The problem is that unless
we can  figure out why the JNA is failing the library will only fall back
to an implementation which does nothing. Is it possible to debug this on
your system?

**Comment by ChandanKumar0125** [comment]
Hi Peter,

After debugging identified that it was not loading the jna as jna platoform was not available. So added the jna-platform-4.2.0 jar and it started working after that. 

Thanks for your prompt reply. I'm going to explore little bit around the thread affinity and your support will be highly appreciated. Thanks again.

Cheers,
Chandan

**Comment by peter-lawrey** [comment]
For the best results, try using affinity on isolated cpus eg linux.

You might like to try this class
https://github.com/OpenHFT/Java-Chronicle/blob/master/chronicle-demo/src/main/java/vanilla/java/processingengine/MicroJitterSampler.java

**Comment by cballock** [comment]
Hi, Peter. I am experiencing this same problem reported by Chandan. But, even after importing the jna-platform-4.2.0 jar, the problem still occurs. Do you know what else could be done?

Disclosure: this is my first time using JNA.

**Comment by cballock** [comment]
Complementing:

Affinity version: 3.0;
SO: Mac OS X Yosemite;
Java version: 1.8.0_65;

**Comment by cballock** [comment]
Hi Peter. I was debbuging your code and noticed that the method getAffinity() in class OSXJNAAffinity always return null. That is what is causing my exception. Please, can you confirm that? If so, how can I use your library in Mac?

**Comment by peter-lawrey** [comment]
It should be noted that CPU Affinity is not supported by the Mac OSX
operating system. While we could work to resolve the error this wouldn't do
what you would want. This is just to keep the functionality consistent as
possible across OSes.

Regards, Peter.
