### ISSUE TITLE
Finalizer warnings

### ISSUE THREAD

**Issue by dongell** [OpenHFT/Java-Thread-Affinity#24]
Using v2.2 on Linux.  After a GC occurs, the following warning is logged for each of the reservable CPUs:

[Finalizer] WARN net.openhft.affinity.AffinityLock - Affinity lock for null was discarded rather than release()d in a controlled manner.

This is occurring because LOCK_INVENTORY is initialized inline with a NoCpuLayout, and then in the static initialization block the layout is overwritten with fromCpuInfo().  The first set of AffinityLock objects are subject to GC, hence the warning logged in finalize().

Should the layout be set only once, from the static block, after checking for /proc/cpuinfo?

**Comment by RobAustin** [comment]
@dongell could you raise a pull request with this change and I'll merge it in
