### ISSUE TITLE
Possible bind issue with AffinityThreadFactory

### ISSUE THREAD

**Issue by aconstnull** [OpenHFT/Java-Thread-Affinity#30]
Hey,

I'm using `AffinityThreadFactory` and noticed something interesting:
Having created a bunch of threads using it, along with isolcpus - I found that only the _first_ thread created by the factory had its `Cpus_allowed_list` updated in /proc. 
If this is expected behaviour - no problems :)
Otherwise, the offender appears to be here in AffinityThreadFactory:
`
@Override
            public void run() {
                AffinityLock al = lastAffinityLock == null ? AffinityLock.acquireLock() : lastAffinityLock.acquireLock(strategies);
`

For the very first created thread, we use 'aquireLock' - which internally sets the 'bind' flag to true:

`
    public static AffinityLock acquireLock() {
        return acquireLock(true);
    }
`
For all subsequently created threads, we use lock.aquireLock(strategies) - which sets the 'bind' flag to **false**:

`
    public AffinityLock acquireLock(AffinityStrategy... strategies) {
        return acquireLock(false, cpuId, strategies);
    }
`

The thread factory doesn't do any further binding related activities with the locks it gets returned.

The result is that the first thread created is bound to its lock's reserved cpu - but no other threads are.

I dropped in a replacement thread factory locally where I explicitly 'bind' the locks after they are returned - and can report that all created threads now report the expected values in `Cpus_allowed_list`.

My 95th percentiles and above just got way better too ;)

Thanks for the great library!

**Comment by aconstnull** [comment]
Related: updates to lastAffinityLock are not synchronised which can cause issues. (The create thread method is synchronised but there is no synchronisation around reading / updating the lastAffinityLock member when working out how to acquire our next lock)

**Comment by maseev** [comment]
Has this problem been fixed by any chance? Looks like this ticket hasn't been getting any attention since October 2016 :worried:
