### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by puntogil** [OpenHFT/Java-Thread-Affinity#32]
hi
 i get:

UnsatisfiedLinkError: software.chronicle.enterprise.internals.impl.NativeAffinity.getProcessId0()I
running these test
affinity/src/test/java/net/openhft/affinity/impl/NativeAffinityImpTest.java 
affinity/src/test/java/net/openhft/ticker/impl/JNIClockTest.java
on
Apache Maven 3.3.9 (NON-CANONICAL_2016-04-07T23:15:34Z_mockbuild; 2016-04-08T01:15:34+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-1.b14.fc24.i386/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.6.6-300.fc24.i686", arch: "i386", family: "unix"

and i tried to build also on an our ARM arch builder, but i get:
net_openhft_ticker_impl_JNIClock.cpp:59:25: error: 'rdtsc' was not declared in this scope
any plan for support other arches?
thanks in advance
regards

**Comment by peter-lawrey** [comment]
Hello puntogil,
   The JNI implementation should work on Linux if the Path is setup to
include the shared library.
    We would like to support ARM buy haven't had the resources to do this
to date.

Regards, Peter.

**Comment by puntogil** [comment]
Fedora Linux support different arches (i386, i486, i586, i686, pentium3, pentium4, athlon, geode, x86_64, sparc, sparcv9, ia64, aarch64, armv3l, armv4b, armv4l, armv4tl, armv5tel, armv5tejl, armv6l, armv6hl, armv7l, armv7hl, armv7hnl, alpha, s390x, ppc, ppc64, ppc64le,  s390, s390x), perhaps you could use our os, to develop your software on/for Unix-like environment
regards

**Comment by peter-lawrey** [comment]
Hello,
  The problem is we need to be able to run tests on each of those hardware
to know the solution works. We are using Unsafe operations which work fine
on x64, but we know don't work the same on ARM.

Regards,
  Peter.
