### ISSUE TITLE
PosixJNAAffinityTest#testGettid fails

### ISSUE THREAD

**Issue by plusterkopp** [OpenHFT/Java-Thread-Affinity#34]
On this CentOS machine (2x18 cores, SMT), I get thread IDs like 121295. This fails when testGettid asserts tid < 2^16. What is the reason for that assumption? Thread#tid is defined as long and set from Thread.threadSeqNumber, which is long, too.

**Comment by peter-lawrey** [comment]
Thread.tid is an incrementing counter for the process starting at 1.
Not to be confused with the thread id given to the thread by the OS.
Typically OSes give thread IDs which are 16-bit however Linux for example
can be tuned to allow more.
It is possible the test isn't valid, it would need to be reviewed.
ᐧ

**Comment by plusterkopp** [comment]
Actually, in **PosixJNAAffinityTest** we have 
`
tid = Thread.currentThread().getId();
...
assertTrue(tid < 1 << 16);
`
with 
`public long getId() {
        return tid;
    }`
in **Thread** and 
`tid = nextThreadID();` in `Thread#init(...);`
is there a native ID, too? Where? And where is `threadSeqNumber` being initialized?

**Comment by peter-lawrey** [comment]
That test only makes sense if the getId() has been overwritten with the
actual OS pid of the thread.
ᐧ
