### ISSUE TITLE
can you add that kind of functionality at runtime java ?

### ISSUE THREAD

**Issue by eix128** [OpenHFT/Java-Thread-Affinity#36]
I want disable 1 core of cpu for OS completely and assign this core to my java thread.
I have seen this stackoverflow solution as "Linux only" and not java based
https://stackoverflow.com/questions/9072060/one-core-exclusively-for-my-process
Can we add these instructions on Thread Affinity as "Native"
Also for Windows and Solaris ?

**Comment by peter-lawrey** [comment]
You can use affinity to bind a thread to a CPU or core however isolating a
cpu is a Linux feature AFAIK and without isolation I haven't found affinity
to make a useful difference.

Regards Peter
