### ISSUE TITLE
Split packages cause error with Java 9

### ISSUE THREAD

**Issue by tbabinski** [OpenHFT/Java-Thread-Affinity#41]
The affinity library defines classes in the `java.lang` package.  This is not allowed in Java 9, since the `java.lang` package is already exported by the `java.base` module

Here is the error:

> error: module affinity reads package java.lang from both java.base and affinity

**Comment by epickrram** [comment]
This is due to the fact that `ThreadTackingGroup` needs to override package-private methods on the `java.lang.ThreadGroup` class.

Java 9 support for Chronicle libraries is on-going, this will be added to the backlog.

**Comment by andrm** [comment]
Can't run my chronicle queue application on Java 10 :(. Is there a workaround for this?

**Comment by dpisklov** [comment]
@andrm Not yet I'm afraid. Our next target Java release we will support is Java 11, which is coming in September (as most commercial clients of ours will be migrating from 8 to 11 after 8 is EOL). At the moment we have no clients who are using versions past Java 8. However if you're interested in commercial support please contact sales@chronicle.software

**Comment by andrm** [comment]
Thanks. Workaround: Run everything on the classpath. Works with Java 10.

**Comment by RobAustin** [comment]
For clarity - This is not required for the 9 java compatibility, in other words this code should run on java 9 but it will only cause an issue if it is compiled with java 9. We are not planning to do this in the near future, so for now closing as wont fix.
