### ISSUE TITLE
cross process Affinity

### ISSUE THREAD

**Issue by ariksher-nex** [OpenHFT/Java-Thread-Affinity#44]
Hi,

I tried to use the AffinityLock.acquireCore(). it looks good and seems that it does lock specific Core to a thread. however, when I run 2 (similar) processes on same machine it looks like the seconds process locks on same Core, as the first app. here are the dumps of 2 apps (I run on my desktop, only 4 cores):

_dump of App 1:_
0: General use CPU
1: Reserved for this application
2: Thread[name1,5,main] alive=true
3: General use CPU

_dump of App 2:_
0: General use CPU
1: Reserved for this application
2: Thread[name3,5,main] alive=true
3: General use CPU

is that on purpose?
I would assume that once core is locked, than other apps won't be able to lock the same core.

Thanks,
Arik

**Comment by epickrram** [comment]
Are you using the latest version from master? Some fixes have been made in this area recently.

If the problem persists, can you share the output of `lscpu` (assuming you're on Linux), and check on the presence and content of any files matching 
`$java.io.tmpdir/cpu-*.lock`

**Comment by ariksher-nex** [comment]
i'm using version 3.1.7 (took it from maven global repo).
my output is when running on windows 10 desktop machine. not linux (yet).

**Comment by epickrram** [comment]
So can you check for files in the temp directory when your program is running and check that you see lock files?

**Comment by ariksher-nex** [comment]
my java.io.tmpdir is C:\Users\asher\AppData\Local\Temp
my process is running but i don't see any file named cpu*.lock

**Comment by epickrram** [comment]
Support for non-Linux platforms is incomplete:

https://github.com/OpenHFT/Java-Thread-Affinity/blob/master/affinity/src/main/java/net/openhft/affinity/LockCheck.java#L145

```
    static void updateCpu(int cpu) {
        if (!IS_LINUX)
            return;
    ....
    }
```

On Windows, there is no handling of CPU reservation between multiple processes. Try your program on a Linux system to see whether the problem occurs there.

**Comment by ariksher-nex** [comment]
ok will try thanks.
