### ISSUE TITLE
If one user holds a lock but doesn't release it, another user can't free it.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Java-Thread-Affinity#48]
Different users should be able to share affinity on a machine.

**Comment by hft-team-city** [comment]
Released in Java-Thread-Affinity-3.1.10 (https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.1.10), BOM-1.16.201 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.201)
