### ISSUE TITLE
Hide Logging

### ISSUE THREAD

**Issue by Chazza** [OpenHFT/Java-Thread-Affinity#56]
Hi,

How would I go ahead with silencing all the debug messages? Any chance you can make this done via a toggle as it's for a public java resource.

Thanks.

**Comment by dpisklov** [comment]
@Chazza we use [slf4j](http://www.slf4j.org/), please refer to the doc on how to change log levels

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.2.3](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.2.3), [BOM-2.19.101](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.101)
