### ISSUE TITLE
Exception | AssertionError

### ISSUE THREAD

**Issue by yooniks** [OpenHFT/Java-Thread-Affinity#59]
Hello! I'm making some application, and when one of my customer run it on his vps, it shows him:
https://hastebin.com/sobozuseco.xml
How can I fix it?

**Comment by dpisklov** [comment]
I don't think it makes much sense to use thread affinity on VPS (which by definition shares resources, and you can't control CPU allocation). So I suggest you simply disable affinity.

**Comment by JerryShea** [comment]
Unfortunately even when trying not to use affinity the AffinityLock static block ends up being called by e.g. VanillaEventLoop. I've made a change so that we log.warn the error and keep going.

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.2.3](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.2.3), [BOM-2.19.101](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.101)
