### ISSUE TITLE
-Daffinity.reserved not working when the bitmask is more than 64 bits longs

### ISSUE THREAD

**Issue by m-anthony** [OpenHFT/Java-Thread-Affinity#67]
Although affinity is working correctly on a 64+ core system, we cannot specify such a bitmask through -Daffinity.reserved
Cf net.openhft.affinity.AffinityLock.getReservedAffinity0()

I fixed the parsing locally and managed to make it work on a 96-core system, I will shortly provide a PR

**Comment by peter-lawrey** [comment]
We have added some support to use a BitSet instead of a long. Can you use a BitSet instead?
