### ISSUE TITLE
Run "mvn package" fail in shell

### ISSUE THREAD

**Issue by yhryyq** [OpenHFT/Java-Thread-Affinity#70]
First, I can run `mvn package` in Ubuntu command line. A part of result as below:

```
[INFO] --- exec-maven-plugin:1.2.1:exec (build-native) @ affinity ---
    g++ -O3 -Wall -shared -fPIC -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/i386/server  -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/jrockit/ -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/i386/jrockit/ -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ppc64le/server -L/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ppc64le/jrockit/ -ljvm -lrt -I /usr/lib/jvm/java-8-openjdk-amd64/include -I /usr/lib/jvm/java-8-openjdk-amd64/include/linux -I ../../../target/classes/../jni software_chronicle_enterprise_internals_impl_NativeAffinity.cpp net_openhft_ticker_impl_JNIClock.cpp -o ../../../target/classes/libCEInternals.so
    [INFO]
    [INFO] --- maven-bundle-plugin:4.2.1:manifest (default) @ affinity ---
```

Then, I write a execute.sh as below:

```
cd work
mvn package
```

When I run execute.sh. I got:

    [INFO] --- exec-maven-plugin:1.2.1:exec (build-native) @ affinity ---
    mkdir -p ../../../target/classes/jni
    javah -force -classpath ../../../target/classes -d ../../../target/classes/../jni software.chronicle.enterprise.internals.impl.NativeAffinity net.openhft.ticker.impl.JNIClock
    g++ -O3 -Wall -shared -fPIC -L/usr/java/default/jre/lib/amd64/server -L/usr/java/default/jre/lib/i386/server  -L/usr/java/default/jre/lib/amd64/jrockit/ -L/usr/java/default/jre/lib/i386/jrockit/ -L/usr/java/default/jre/lib/ppc64le/server -L/usr/java/default/jre/lib/ppc64le/jrockit/ -ljvm -lrt -I /usr/java/default/include -I /usr/java/default/include/linux -I ../../../target/classes/../jni software_chronicle_enterprise_internals_impl_NativeAffinity.cpp net_openhft_ticker_impl_JNIClock.cpp -o ../../../target/classes/libCEInternals.so
    software_chronicle_enterprise_internals_impl_NativeAffinity.cpp:21:10: fatal error: jni.h: No such file or directory
       21 | #include <jni.h>
          |          ^~~~~~~
    compilation terminated.
    net_openhft_ticker_impl_JNIClock.cpp:21:10: fatal error: jni.h: No such file or directory
       21 | #include <jni.h>
          |          ^~~~~~~
    compilation terminated.
    make: *** [/mnt/c/Users/yhryy/Desktop/TryRealProj/projects/Java-Thread-Affinity-ea/work/affinity/src/main/c/Makefile:41: ../../../target/classes/libCEInternals.so] Error 1
    [INFO] ------------------------------------------------------------------------

**Comment by JerryShea** [comment]
@yhryyq this works for me on my ubuntu machine. Maybe something environmental?
