### ISSUE TITLE
Affinity is able to be acquired on cores locked by other processes

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Java-Thread-Affinity#79]
There's a bug in `AffinityLock.acquireLock` where locks held by other processes are not visible, meaning threads from separate processes are able to acquire a lock on the same core.

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.21ea80](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.21ea80), [BOM-2.22ea40](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea40)
