### ISSUE TITLE
Can't lock to CPU 0

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Java-Thread-Affinity#90]
I understand this is probably not something you'd do in the real world, but the code has baked into it the inability to lock to core 0.

We're attempting to write a core-to-core latency test and we're unable to get a number for any pair involving zero.

I'm not sure if the reason for disallowing it is because it's not recommended, or there's another good reason?

**Comment by nicktindall** [comment]
Some places where the limitation is baked in:

https://github.com/OpenHFT/Java-Thread-Affinity/blob/82dc0bb50ee729a135798977c07100a1e80fcab3/affinity/src/main/java/net/openhft/affinity/AffinityLock.java#L125-L126

https://github.com/OpenHFT/Java-Thread-Affinity/blob/82dc0bb50ee729a135798977c07100a1e80fcab3/affinity/src/main/java/net/openhft/affinity/AffinityLock.java#L276-L279

https://github.com/OpenHFT/Java-Thread-Affinity/blob/82dc0bb50ee729a135798977c07100a1e80fcab3/affinity/src/main/java/net/openhft/affinity/LockInventory.java#L123

**Comment by nicktindall** [comment]
It feels like we should let `net.openhft.affinity.AffinityLock#RESERVED_AFFINITY` drive whether a core is reservable exclusively, so we can remove the core-0 restriction more easily if we want to?

**Comment by JerryShea** [comment]
@peter-k-lawrey is of the opinion that we should not allow core 0 to be isolated as the kernel is likely to be running there
