### ISSUE TITLE
Handle ClosedByInterruptException for when acquireLock() is interrupted

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Java-Thread-Affinity#92]

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.23ea0](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.23ea0), [BOM-2.23ea104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea104)
