### ISSUE TITLE
log warning instead of throw exception for too high cpuId

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Java-Thread-Affinity#93]
This restores previous behaviour

**Comment by hft-team-city** [comment]
Released in [Java-Thread-Affinity-3.23ea0](https://github.com/OpenHFT/Java-Thread-Affinity/releases/Java-Thread-Affinity-3.23ea0), [BOM-2.23ea104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea104)
